name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  vapor:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Composer
      run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
      env:
        NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
        NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}

    - uses: ubient/laravel-vapor-action@master
      needs: [php-cs-fixer, prettier]
      env:
        VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
      with:
        args: "deploy production"
