name: Format (PHP)

on:
    push:
        branches:
            - master
    pull_request:
        paths:
            - '**.php'

jobs:
     php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                ref: ${{ github.head_ref }}

            - name: Setup Composer
              run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
              env:
                NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
                NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}

            - name: Install
              run: composer install

            - name: Run php-cs-fixer
              run: composer format

            - uses: stefanzweifel/git-auto-commit-action@v4.1.0
                with:
                  commit_message: Apply php-cs-fixer changes
                  branch: ${{ github.head_ref }}
